### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by soofstad** [equinor/template-fastapi-react#8]
API
- [x] Health check endpoint
- [x] Authentication
- [x] Dockerfile
- [x] Poetry
- [x] Unit tests
- [x] Integration tests
- [x] OpenAPI spec
- [x] Clean Architecture basic structure

Web
- [x] Hello world
- [x] Dockerfile
- [x] OAuth2 login
- [x] Unit tests (jest)
- [ ] React components render tests (jest-enzyme/enzyme/somethingelse?)
- [x] equinor icon/favicon

Pre-commit
- [x] Linting python
- [x] Linting js
- [x] Formatting python
- [x] Formatting JS
- [x] Typechecks Python
- [x] Typescript checks
- [x] Dependency scan (python safety)
- [x] Static code scan (bandit, anything for JS)
- [x] Unit tests

CI/CD - Deploy
- [x] Radix config
- [x] Run pre-commit + uTests and iTests
- [x] Build images
- [x] Push images
- [x] Deploy
